### PR TITLE
[4.0] Fix Issue Session timer not working.

### PR DESCRIPTION
**Pull request by Anu1601CS**
Pull Request for Issue  #18921

### Summary of Changes
Changes in :
<code>src\Session.php</code>

In the  Start a session and Restart an expired or locked session functions.

Added : Validate session if the session isn't valid and if it expired then try to restart else destroy it.

### Testing Instructions
Apply patch and do nothing for period of time you set in session timer (lifetime).

##Expected result

auto logout.

##Actual result

still active.

### CODE REVIEW

**Comment by Anu1601CS** [comment]
@mbabker can you check issue is fixed or not.

**Comment by mbabker** [comment]
I plan to look at it this weekend.

**Comment by Anu1601CS** [comment]
@mbabker I am waiting for review.

**Comment by Anu1601CS** [comment]
@mbabker Thanks

**Pull request merged**
